_: with _; [
  packages.nixpkgs.awscli
  packages.nixpkgs.bat
  packages.nixpkgs.bind
  packages.nixpkgs.binutils
  packages.nixpkgs.black
  packages.nixpkgs.cachix
  packages.nixpkgs.coreutils
  packages.nixpkgs.curl
  packages.nixpkgs.dconf2nix
  packages.nixpkgs.dmenu
  packages.nixpkgs.gcc
  packages.nixpkgs.ghc
  packages.nixpkgs.gnome.dconf-editor
  packages.nixpkgs.gnumake
  packages.nixpkgs.gnupg
  packages.nixpkgs.hugo
  packages.nixpkgs.jq
  packages.nixpkgs.just
  packages.nixpkgs.lsof
  packages.nixpkgs.mypy
  packages.nixpkgs.niv
  packages.nixpkgs.nix-index
  packages.nixpkgs.nix-info
  packages.nixpkgs.nixos-generators
  packages.nixpkgs.nixpkgs-fmt
  packages.nixpkgs.nixpkgs-review
  packages.nixpkgs.optipng
  packages.nixpkgs.parallel
  packages.nixpkgs.parted
  packages.nixpkgs.python38
  packages.nixpkgs.python38Packages.isort
  packages.nixpkgs.shfmt
  packages.nixpkgs.sops
  packages.nixpkgs.vscode
  packages.nixpkgs.wirelesstools
  packages.nixpkgs.wpa_supplicant
  packages.nixpkgs.xclip
  packages.nixpkgs.yq
]
